# Generated by Django 3.2.4 on 2022-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_shiftingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftingaddress',
            name='account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shiftingaddress',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
