# Generated by Django 3.2 on 2022-04-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_mpesacallbacks_mpesacalls_mpesapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftingrequest',
            name='caretaker',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
    ]
