# Generated by Django 3.2 on 2022-04-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20220421_0201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='ChangePackage',
        ),
    ]
