# Generated by Django 3.2 on 2022-04-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_rename_packages_changepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phonenum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tickets',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
